# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZAuhBguO3oYj-tbzw5Nq9ggtc0jWKsw
"""

print("cgcek")

"""LETS MAKE A LIST"""

#list of roll.no

my_friend = ["Tenzin", "Dekar", "Trisha", "Bajpai"]

print(my_friend)

"""APPEND OR ADDING NEW ITEMS TO THE LIST"""

print(my_friend)

my_friend.append("Rozina")
print(my_friend)

my_friend.insert(2, 109)
print(my_friend)

#Remove the item from the list

my_friend.pop(2)
print(my_friend)

#Remove - specify

my_friend.remove("Rozina")
print(my_friend)

"""SHOPPING CART"""

print("WELCOME TO ROZINA MART")
print("="*20)

shopping_cart = ["shoto","chrollo","satoru","itachi"]
print(shopping_cart)
print("="*20)

add_item = "L"
shopping_cart.append(add_item)
print(shopping_cart)
print("="*20)

print("Spotify Liked songs")
print("="*20)

liked_songs = ["Strong","Sunsetz","What makes you beautiful","Winter Bear"]
print(liked_songs)
print("="*65)

add_song = "Perfect"
liked_songs.append(add_song)
print(liked_songs)
print("="*76)